### ISSUE TITLE
bin, lib: support node

### ISSUE THREAD

**Issue by ghalle** [amokjs/amok#145]
It's currently possible to use the chrome debugging protocol with node.js using https://github.com/node-inspector/node-inspector.

This could allow amok to work on nodejs. Although it doesn't seem to be a documented use case for node-inspector, you can connect to node-inspector yourself using node-rdbg (or anything similar that implements the chrome debug protocol) instead of using the devtools it hosts. I've personally tested it doing something similar to amok (setScriptSource when file changes) and it seems to work fine.

Knowing that we could probably have a --node flag or similar for amok that spawns node-inspector.
Other changes would also be needed like using process.on instead of addEventListener if its nodejs.
##

**Comment by caspervonb** [comment]
:+1: for node.

I've playing the waiting game and looking if node will support the chrome protocol directly in node.

Some of the io.js folks were discussing this a couple of months back on the nodeup podcast. Today there are discussions like this one https://github.com/nodejs/node/issues/2546#issuecomment-135293812 taking place.

**Comment by caspervonb** [comment]
There's also https://github.com/jkrems/bugger which feels more like "just an adapter", but I think either a canonical adapter or native support will come from the node discussions.

**Comment by ghalle** [comment]
So perhaps there should still be a --node flag but that would be to tell amok to launch whatever file it was passed using node with the --debug-brk flag

so amok index.js --node

**Comment by ghalle** [comment]
So the only thing to change in amok would be to make sure everything works for both browsers and node, and then when native chrome debugging protocol works for node, amok index.js --node will just work out of the box, while meanwhile it can still work but it would be up to the user to open node-inspector themselves or bugger or any other adapter.

**Comment by caspervonb** [comment]
We should probably not start with --debug-brk since it's hard to opt-out, the port, host etc would have to be set tho.

Since `browser_process` can infer the browser type from the executable, which it could not do before I'm likely to change the environment variables to be just `BROWSER` and `BROWSER_FLAGS` in the next major. With that I want to change the behaviour of the --browser flag to just spawn a default browser if none is provided.

Meaning that
```
$ amok --browser
```

Will look open the browser specified by the `BROWSER` environment variable, if none is found it'll detect the first one. It'll also use the arguments in BROWSER_FLAGS as additional command line arguments when spawning the browser. The different being that there will be no more pairs of excess environment variables.

So I'm thinking we do the same with node, spawn the executable found in a NODE environment variable, if none when just do a default search. Additional command line options specified by a `NODE_FLAGS` environment variable.

**Comment by caspervonb** [comment]
Also, should compilers be supported?

**Comment by ghalle** [comment]
I think compilers should be supported this would allow to use amokify with node for example. Both browserify and webpack bundles can run in node with certain options.

**Comment by caspervonb** [comment]
Amokify would preferably be ported to commonjs, having actual small source files is the optimal way to use Amok as every thing goes over the wire. Once you huge bundles you have to split them up into smaller bundles, like your code and dependencies, It will still work but somewhere around 7-10mb things get very slow.

**Comment by caspervonb** [comment]
Decided to take this on for the next release, we'll do a version check and conditionally launch an adapter.

**Comment by caspervonb** [comment]
So I'm having issues getting responses sometimes, e.g we'll call `Console.enable` and never get the response that signals error success.

All in all, node-inspector is a feasible bridge and worst case scenario we have to PR. Stay tuned for the node branch in a couple of days.

**Comment by caspervonb** [comment]
Turns out node-inspector crashes, **alot**. Even when used standalone.

**Comment by caspervonb** [comment]
Bugger has moved and is being worked on.
https://github.com/buggerjs/bugger/

**Comment by caspervonb** [comment]
And it works! :grin:

**Comment by caspervonb** [comment]
First pass https://github.com/caspervonb/amok/commit/3aa7caa42011fa28cc05e02c447596f75a5ddd60
